// Copyright 2019 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_heart_rate_measurement          16
#define gattdb_body_sensor_location            19
#define gattdb_heart_rate_control_point         21
#define gattdb_manufacturer_name_string         24
#define gattdb_model_number_string             26
#define gattdb_serial_number_string            28
#define gattdb_hardware_revision_string         30
#define gattdb_firmware_revision_string         32
#define gattdb_software_revision_string         34
#define gattdb_system_id                       36
#define gattdb_ieee_11073_20601_regulatory_certification_data_list         38
#define gattdb_pnp_id                          40

#endif
